version: "3.8"

networks:
  local:
    driver: bridge

services:
  local-project:
    build: ./docker
    volumes:
      - ./:/var/www/html/localhost
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - local
    environment:
      PHP_IDE_CONFIG: "serverName=Project"
      XDEBUG_SESSION: PHPSTORM
    container_name: local_project

  local-nginx:
    image: nginx:1.23
    volumes:
      - ./:/var/www/html/localhost
      - ./docker/nginx/localhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local
    ports:
      - "8081:80"
    container_name: local_nginx
    depends_on:
      - local-project